#ifndef ECLAY_PROCESSOR_EVENT_SYSTEM_H
#define ECLAY_PROCESSOR_EVENT_SYSTEM_H

#include "processor/sam.h"

#include <stdbool.h>
#include <stdint.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef uint8_t processor_event_system_channel_t;
#define PROCESSOR_EVENT_SYSTEM_NUM_CHANNELS   EVSYS_CHANNELS

typedef enum
{
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_NONE  = 0x0,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_0     = 0x1,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_1     = 0x2,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_2     = 0x3,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_3     = 0x4,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_4     = 0x5,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_5     = 0x6,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_6     = 0x7,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_7     = 0x8,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_8     = 0x9,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_9     = 0xA,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_10    = 0xB,
  PROCESSOR_EVENT_SYSTEM_USER_CHANNEL_11    = 0xC,
} processor_event_system_user_channel_t;

typedef enum
{
  PROCESSOR_EVENT_SYSTEM_EDGE_NO_OUTPUT = EVSYS_CHANNEL_EDGSEL_NO_EVT_OUTPUT_Val,
  PROCESSOR_EVENT_SYSTEM_EDGE_RISING    = EVSYS_CHANNEL_EDGSEL_RISING_EDGE_Val,
  PROCESSOR_EVENT_SYSTEM_EDGE_FALLING   = EVSYS_CHANNEL_EDGSEL_FALLING_EDGE_Val,
  PROCESSOR_EVENT_SYSTEM_EDGE_BOTH      = EVSYS_CHANNEL_EDGSEL_BOTH_EDGES_Val
} processor_event_system_edge_t;

typedef enum
{
  PROCESSOR_EVENT_SYSTEM_PATH_SYNCHRONOUS    = EVSYS_CHANNEL_PATH_SYNCHRONOUS_Val,
  PROCESSOR_EVENT_SYSTEM_PATH_RESYNCHRONIZED = EVSYS_CHANNEL_PATH_RESYNCHRONIZED_Val,
  PROCESSOR_EVENT_SYSTEM_PATH_ASYNCHRONOUS   = EVSYS_CHANNEL_PATH_ASYNCHRONOUS_Val
} processor_event_system_path_t;

typedef enum
{
  PROCESSOR_EVENT_SYSTEM_GENERATOR_NONE         = 0x00,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_CMP0     = EVSYS_ID_GEN_RTC_CMP_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_CMP1     = EVSYS_ID_GEN_RTC_CMP_1,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_OVF      = EVSYS_ID_GEN_RTC_OVF,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_PER0     = EVSYS_ID_GEN_RTC_PER_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_PER1     = EVSYS_ID_GEN_RTC_PER_1,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_PER2     = EVSYS_ID_GEN_RTC_PER_2,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_PER3     = EVSYS_ID_GEN_RTC_PER_3,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_PER4     = EVSYS_ID_GEN_RTC_PER_4,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_PER5     = EVSYS_ID_GEN_RTC_PER_5,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_PER6     = EVSYS_ID_GEN_RTC_PER_6,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_RTC_PER7     = EVSYS_ID_GEN_RTC_PER_7,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT0  = EVSYS_ID_GEN_EIC_EXTINT_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT1  = EVSYS_ID_GEN_EIC_EXTINT_1,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT2  = EVSYS_ID_GEN_EIC_EXTINT_2,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT3  = EVSYS_ID_GEN_EIC_EXTINT_3,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT4  = EVSYS_ID_GEN_EIC_EXTINT_4,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT5  = EVSYS_ID_GEN_EIC_EXTINT_5,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT6  = EVSYS_ID_GEN_EIC_EXTINT_6,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT7  = EVSYS_ID_GEN_EIC_EXTINT_7,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT8  = EVSYS_ID_GEN_EIC_EXTINT_8,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT9  = EVSYS_ID_GEN_EIC_EXTINT_9,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT10 = EVSYS_ID_GEN_EIC_EXTINT_10,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT11 = EVSYS_ID_GEN_EIC_EXTINT_11,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT12 = EVSYS_ID_GEN_EIC_EXTINT_12,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT13 = EVSYS_ID_GEN_EIC_EXTINT_13,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT14 = EVSYS_ID_GEN_EIC_EXTINT_14,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_EIC_EXTINT15 = EVSYS_ID_GEN_EIC_EXTINT_15,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_DMAC_CH0     = EVSYS_ID_GEN_DMAC_CH_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_DMAC_CH1     = EVSYS_ID_GEN_DMAC_CH_1,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_DMAC_CH2     = EVSYS_ID_GEN_DMAC_CH_2,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_DMAC_CH3     = EVSYS_ID_GEN_DMAC_CH_3,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC0_OVF     = EVSYS_ID_GEN_TCC0_OVF,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC0_TRG     = EVSYS_ID_GEN_TCC0_TRG,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC0_CNT     = EVSYS_ID_GEN_TCC0_CNT,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC0_MCX0    = EVSYS_ID_GEN_TCC0_MCX_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC0_MCX1    = EVSYS_ID_GEN_TCC0_MCX_1,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC0_MCX2    = EVSYS_ID_GEN_TCC0_MCX_2,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC0_MCX3    = EVSYS_ID_GEN_TCC0_MCX_3,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC1_OVF     = EVSYS_ID_GEN_TCC1_OVF,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC1_TRG     = EVSYS_ID_GEN_TCC1_TRG,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC1_CNT     = EVSYS_ID_GEN_TCC1_CNT,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC1_MCX0    = EVSYS_ID_GEN_TCC1_MCX_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC1_MCX1    = EVSYS_ID_GEN_TCC1_MCX_1,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC2_OVF     = EVSYS_ID_GEN_TCC2_OVF,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC2_TRG     = EVSYS_ID_GEN_TCC2_TRG,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC2_CNT     = EVSYS_ID_GEN_TCC2_CNT,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC2_MCX0    = EVSYS_ID_GEN_TCC2_MCX_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TCC2_MCX1    = EVSYS_ID_GEN_TCC2_MCX_1,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC3_OVF      = EVSYS_ID_GEN_TC3_OVF,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC3_MC0      = EVSYS_ID_GEN_TC3_MCX_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC3_MC1      = EVSYS_ID_GEN_TC3_MCX_1,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC4_OVF      = EVSYS_ID_GEN_TC4_OVF,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC4_MC0      = EVSYS_ID_GEN_TC4_MCX_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC4_MC1      = EVSYS_ID_GEN_TC4_MCX_1,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC5_OVF      = EVSYS_ID_GEN_TC5_OVF,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC5_MC0      = EVSYS_ID_GEN_TC5_MCX_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_TC5_MC1      = EVSYS_ID_GEN_TC5_MCX_1,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_ADC_RESRDY   = EVSYS_ID_GEN_ADC_RESRDY,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_ADC_WINMON   = EVSYS_ID_GEN_ADC_WINMON,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_AC_COMP0     = EVSYS_ID_GEN_AC_COMP_0,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_AC_COMP1     = EVSYS_ID_GEN_AC_COMP_1,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_AC_WIN0      = EVSYS_ID_GEN_AC_WIN_0,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_DAC_EMPTY    = EVSYS_ID_GEN_DAC_EMPTY,

  PROCESSOR_EVENT_SYSTEM_GENERATOR_PTC_EOC      = 0x48,
  PROCESSOR_EVENT_SYSTEM_GENERATOR_PTC_WCOMP    = 0x49,
} processor_event_system_generator_t;

typedef enum
{
  PROCESSOR_EVENT_SYSTEM_USER_DMAC_CH0   = EVSYS_ID_USER_DMAC_CH_0,
  PROCESSOR_EVENT_SYSTEM_USER_DMAC_CH1   = EVSYS_ID_USER_DMAC_CH_1,
  PROCESSOR_EVENT_SYSTEM_USER_DMAC_CH2   = EVSYS_ID_USER_DMAC_CH_2,
  PROCESSOR_EVENT_SYSTEM_USER_DMAC_CH3   = EVSYS_ID_USER_DMAC_CH_3,

  PROCESSOR_EVENT_SYSTEM_USER_TCC0_EV0   = EVSYS_ID_USER_TCC0_EV_0,
  PROCESSOR_EVENT_SYSTEM_USER_TCC0_EV1   = EVSYS_ID_USER_TCC0_EV_1,
  PROCESSOR_EVENT_SYSTEM_USER_TCC0_MC0   = EVSYS_ID_USER_TCC0_MC_0,
  PROCESSOR_EVENT_SYSTEM_USER_TCC0_MC1   = EVSYS_ID_USER_TCC0_MC_1,
  PROCESSOR_EVENT_SYSTEM_USER_TCC0_MC2   = EVSYS_ID_USER_TCC0_MC_2,
  PROCESSOR_EVENT_SYSTEM_USER_TCC0_MC3   = EVSYS_ID_USER_TCC0_MC_3,

  PROCESSOR_EVENT_SYSTEM_USER_TCC1_EV0   = EVSYS_ID_USER_TCC1_EV_0,
  PROCESSOR_EVENT_SYSTEM_USER_TCC1_EV1   = EVSYS_ID_USER_TCC1_EV_1,
  PROCESSOR_EVENT_SYSTEM_USER_TCC1_MC0   = EVSYS_ID_USER_TCC1_MC_0,
  PROCESSOR_EVENT_SYSTEM_USER_TCC1_MC1   = EVSYS_ID_USER_TCC1_MC_1,

  PROCESSOR_EVENT_SYSTEM_USER_TCC2_EV0   = EVSYS_ID_USER_TCC2_EV_0,
  PROCESSOR_EVENT_SYSTEM_USER_TCC2_EV1   = EVSYS_ID_USER_TCC2_EV_1,
  PROCESSOR_EVENT_SYSTEM_USER_TCC2_MC0   = EVSYS_ID_USER_TCC2_MC_0,
  PROCESSOR_EVENT_SYSTEM_USER_TCC2_MC1   = EVSYS_ID_USER_TCC2_MC_1,

  PROCESSOR_EVENT_SYSTEM_USER_TC3        = EVSYS_ID_USER_TC3_EVU,

  PROCESSOR_EVENT_SYSTEM_USER_TC4        = EVSYS_ID_USER_TC4_EVU,

  PROCESSOR_EVENT_SYSTEM_USER_TC5        = EVSYS_ID_USER_TC5_EVU,

  PROCESSOR_EVENT_SYSTEM_USER_ADC_START  = EVSYS_ID_USER_ADC_START,
  PROCESSOR_EVENT_SYSTEM_USER_ADC_SYNC   = EVSYS_ID_USER_ADC_SYNC,

  PROCESSOR_EVENT_SYSTEM_USER_AC_COMP0   = EVSYS_ID_USER_AC_SOC_0,
  PROCESSOR_EVENT_SYSTEM_USER_AC_COMP1   = EVSYS_ID_USER_AC_SOC_0,

  PROCESSOR_EVENT_SYSTEM_USER_DAC_START  = EVSYS_ID_USER_DAC_START,

  PROCESSOR_EVENT_SYSTEM_USER_PTC_STCONV = 0x1C,
} processor_event_system_user_t;

typedef void (*processor_event_system_detect_callback_t)( processor_event_system_channel_t channel );

typedef void (*processor_event_system_overrun_callback_t)( processor_event_system_channel_t channel );


void PROCESSOR_EVENT_SYSTEM_Initialize( void );

void PROCESSOR_EVENT_SYSTEM_User_Set(
    processor_event_system_user_t user,
    processor_event_system_user_channel_t channel
  );

void PROCESSOR_EVENT_SYSTEM_Generator_Set(
    processor_event_system_generator_t generator,
    processor_event_system_channel_t channel,
    processor_event_system_edge_t edge,
    processor_event_system_path_t path
  );

void PROCESSOR_EVENT_SYSTEM_SoftwareTrigger(
    processor_event_system_channel_t channel
  );

bool PROCESSOR_EVENT_SYSTEM_isChannelBusy(
    processor_event_system_channel_t channel
  );

bool PROCESSOR_EVENT_SYSTEM_isChannelUserReady(
    processor_event_system_channel_t channel
  );

void PROCESSOR_EVENT_SYSTEM_EventDetectCallback_Set(
    processor_event_system_channel_t channel,
    processor_event_system_detect_callback_t callback
  );

void PROCESSOR_EVENT_SYSTEM_OverrunCallback_Set(
    processor_event_system_channel_t channel,
    processor_event_system_overrun_callback_t callback
  );

void PROCESSOR_EVENT_SYSTEM_EventDetectInterruptEnable_Set(
    processor_event_system_channel_t channel,
    bool enable
  );

void PROCESSOR_EVENT_SYSTEM_OverrunInterruptEnable_Set(
    processor_event_system_channel_t channel,
    bool enable
  );

bool PROCESSOR_EVENT_SYSTEM_EventDetectInterruptFlag_Get(
    processor_event_system_channel_t channel
  );

bool PROCESSOR_EVENT_SYSTEM_OverrunInterruptFlag_Get(
    processor_event_system_channel_t channel
  );

void PROCESSOR_EVENT_SYSTEM_EventDetectInterruptFlag_Clear(
    processor_event_system_channel_t channel
  );

void PROCESSOR_EVENT_SYSTEM_OverrunInterruptFlag_Clear(
    processor_event_system_channel_t channel
  );


#ifdef __cplusplus
}
#endif

#endif  // ECLAY_PROCESSOR_PORT_H
