#ifndef ECLAY_HRI_PM_H
#define ECLAY_HRI_PM_H

#include <sam.h>

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef enum {
  HRI_PM_SYSTEM_CLOCK_CPU,
  HRI_PM_SYSTEM_CLOCK_AHB,
  HRI_PM_SYSTEM_CLOCK_APBA,
  HRI_PM_SYSTEM_CLOCK_APBB,
  HRI_PM_SYSTEM_CLOCK_APBC,
} hri_pm_system_clock_t;

typedef enum {
  HRI_PM_CPU_PRESCALE_DIV1 = PM_CPUSEL_CPUDIV_DIV1_Val,
  HRI_PM_CPU_PRESCALE_DIV2 = PM_CPUSEL_CPUDIV_DIV2_Val,
  HRI_PM_CPU_PRESCALE_DIV4 = PM_CPUSEL_CPUDIV_DIV4_Val,
  HRI_PM_CPU_PRESCALE_DIV8 = PM_CPUSEL_CPUDIV_DIV8_Val,
  HRI_PM_CPU_PRESCALE_DIV16 = PM_CPUSEL_CPUDIV_DIV16_Val,
  HRI_PM_CPU_PRESCALE_DIV32 = PM_CPUSEL_CPUDIV_DIV32_Val,
  HRI_PM_CPU_PRESCALE_DIV64 = PM_CPUSEL_CPUDIV_DIV64_Val,
  HRI_PM_CPU_PRESCALE_DIV128 = PM_CPUSEL_CPUDIV_DIV128_Val,
} hri_pm_cpu_prescale_t;

typedef enum {
  HRI_PM_PERIPHERAL_CLOCK_AHB_HPB0,
  HRI_PM_PERIPHERAL_CLOCK_AHB_HPB1,
  HRI_PM_PERIPHERAL_CLOCK_AHB_HPB2,
  HRI_PM_PERIPHERAL_CLOCK_AHB_DSU,
  HRI_PM_PERIPHERAL_CLOCK_AHB_NVMCTRL,
  HRI_PM_PERIPHERAL_CLOCK_AHB_DMAC,
  HRI_PM_PERIPHERAL_CLOCK_AHB_USB,
  HRI_PM_PERIPHERAL_CLOCK_APBA_PAC0,
  HRI_PM_PERIPHERAL_CLOCK_APBA_PM,
  HRI_PM_PERIPHERAL_CLOCK_APBA_SYSCTRL,
  HRI_PM_PERIPHERAL_CLOCK_APBA_GCLK,
  HRI_PM_PERIPHERAL_CLOCK_APBA_WDT,
  HRI_PM_PERIPHERAL_CLOCK_APBA_RTC,
  HRI_PM_PERIPHERAL_CLOCK_APBA_EIC,
  HRI_PM_PERIPHERAL_CLOCK_APBB_PAC1,
  HRI_PM_PERIPHERAL_CLOCK_APBB_DSU,
  HRI_PM_PERIPHERAL_CLOCK_APBB_NVMCTRL,
  HRI_PM_PERIPHERAL_CLOCK_APBB_PORT,
  HRI_PM_PERIPHERAL_CLOCK_APBB_DMAC,
  HRI_PM_PERIPHERAL_CLOCK_APBB_USB,
  HRI_PM_PERIPHERAL_CLOCK_APBC_PAC2,
  HRI_PM_PERIPHERAL_CLOCK_APBC_EVSYS,
  HRI_PM_PERIPHERAL_CLOCK_APBC_SERCOM0,
  HRI_PM_PERIPHERAL_CLOCK_APBC_SERCOM1,
  HRI_PM_PERIPHERAL_CLOCK_APBC_SERCOM2,
  HRI_PM_PERIPHERAL_CLOCK_APBC_SERCOM3,
  HRI_PM_PERIPHERAL_CLOCK_APBC_SERCOM4,
  HRI_PM_PERIPHERAL_CLOCK_APBC_SERCOM5,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TCC0,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TCC1,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TCC2,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TC3,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TC4,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TC5,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TC6,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TC7,
  HRI_PM_PERIPHERAL_CLOCK_APBC_ADC,
  HRI_PM_PERIPHERAL_CLOCK_APBC_AC,
  HRI_PM_PERIPHERAL_CLOCK_APBC_DAC,
  HRI_PM_PERIPHERAL_CLOCK_APBC_PTC,
  HRI_PM_PERIPHERAL_CLOCK_APBC_I2S,
  HRI_PM_PERIPHERAL_CLOCK_APBC_AC1,
  HRI_PM_PERIPHERAL_CLOCK_APBC_TCC3,
} hri_pm_peripheral_clock_t;

typedef enum {
  HRI_PM_SLEEP_CPU_STOP = PM_SLEEP_IDLE_CPU_Val,
  HRI_PM_SLEEP_CPU_AHB_STOP = PM_SLEEP_IDLE_AHB_Val,
  HRI_PM_SLEEP_CPU_AHB_APB_STOP = PM_SLEEP_IDLE_APB_Val,
} hri_pm_sleep_mode_t;


static inline void HRI_PM_SystemClockPrescale_Set( hri_pm_system_clock_t clock, hri_pm_cpu_prescale_t prescale );

static inline void HRI_PM_PeripheralClock_Enable( hri_pm_peripheral_clock_t clock );
static inline void HRI_PM_PeripheralClock_Disable( hri_pm_peripheral_clock_t clock );

static inline void HRI_PM_SleepMode_Set( hri_pm_sleep_mode_t mode );



#define INCLUDE_HRI_PM_INLINE_H
#include "src/hri_pm_inline.h"
#undef INCLUDE_HRI_PM_INLINE_H


#ifdef __cplusplus
}
#endif

#endif  // ECLAY_HRI_PM_H
